app/models.py
from . import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash,check_password_hash
from datetime import datetime



class Books:
    '''
    Books class to define the book objects
    '''
    def __init__(self, rank, title,author,poster, description, publisher):
        self.rank = rank
        self.title = title
        self.author = author
        self.poster = poster
        self.description = description
        self.publisher = publisher
        
class Preview:
    '''
    Show book previews
    
    '''
    
    def __init__(self,rank, title,author,poster, description, publisher):
        self.rank = rank
        self.title = title
        self.author = author
        self.poster = poster
        self.description = description
        self.publisher = publisher
        
        
    
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
class User(UserMixin,db.Model):
    
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)

    username = db.Column(db.String(255),index = True)

    email = db.Column(db.String(255),unique = True,index = True)

    image_file = db.Column(db.String(255), nullable=False, default='default.jpg')

    password_hash = db.Column(db.String(255))
    
    
    comment = db.relationship('Comment',backref = 'user',lazy = "dynamic")
    @property
    def password(self):
        raise AttributeError("You cannot read the password attribute")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)
    
   

   

    def __repr__(self):

        return f'User {self.username}'
    


class Comment(db.Model):

    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key = True)

    # book_rank = db.Column(db.Integer, db.ForeignKey("book.rank"))

    title = db.Column(db.String(255))

    comment = db.Column(db.String(255))

    posted = db.Column(db.DateTime,default=datetime.utcnow)

    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    @classmethod

    def get_comments(cls, id):

        comments = Comment.query.filter_by(book_rank = id).all()

        return comments

    def delete_comment(self):

        db.session.delete(self)

        db.session.commit()
        
        

app/main/forms.py
from flask_wtf import FlaskForm
from flask_login import current_user, UserMixin
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_wtf.file import FileField, FileAllowed
from ..models import User

class CommentForm(FlaskForm):
    
    title = StringField('Comment title', validators = [DataRequired()])

    comment = TextAreaField('Comment review')

    submit = SubmitField('Submit')
    
class UpdateAccountForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png', 'jpec'])])
    submit = SubmitField('Update')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('That email is taken. Please choose a different one.')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options,DevConfig
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_wtf.csrf import CSRFProtect




#Initiating app extensions
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
bootstrap = Bootstrap()
db = SQLAlchemy()
csrf = CSRFProtect()


def create_app(config_name):
    
    app = Flask(__name__)
    
    app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql+psycopg2://brian:12345 @localhost/book'
    
    
      # Creating the app configurations
    app.config.from_object(config_options[config_name])
    
    
    
    
    #Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    csrf.init_app(app)
    
    
    
    #Registering the auth Blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    
    
    # Registering the  main Blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    # Setting config
    # from .request import configure_request
    # configure_request(app)
    app.config.from_object(DevConfig)
    app.config['SECRET_KEY'] = 'online5'
    app.config['WTF_CSRF_SECRET_KEY'] = 'online5'
    
    
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint("main",__name__)
from . import views

app/main/views.py
from flask import render_template, request, redirect, url_for, abort, current_app, flash
from PIL import Image
from . import main
from ..import db
from ..request import get_books,get_book
from .forms import CommentForm, UpdateAccountForm
from ..models import Comment, User, Books, Preview
from flask_login import login_required, current_user
import os
import secrets




@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    book = get_books()
    title = 'Home - Welcome to the best  Online Library'
    
    
    return render_template('index.html', title=title, book=book)

@main.route('/comments/<book_rank>')

@login_required

def comments(book_rank):

    book = Book.query.filter_by(rank = book_rank).first()

    comments = Comment.query.filter_by(book_rank = book.rank).order_by(Comment.posted.desc())

    return render_template('comments.html', book = book, comments = comments)


@main.route('/book/comment/new/<book_rank>', methods = ['GET', 'POST'])

@login_required

def new_comment(book_rank):

    form = CommentForm()

    book = Book.query.filter_by(rank = book_rank).first()

    comment = Comment()

    if form.validate_on_submit():

        comment.title = form.title.data

        comment.comment = form.comment.data

        comment.book_rank = book_rank

        comment.user_id = current_user.id


        db.session.add(comment)

        db.session.commit()

        return redirect(url_for('main.comments', book_rank = book_rank ))

    return render_template('new_comment.html', comment_form = form)


@main.route("/review/")
@login_required
def review():
    preview = get_book()

    '''
    View root page function that returns the index page and its data
    '''
    title = 'Preview - Welcome to the best  Online Library'
    # preview = Preview.query.filter_by(book_rank = rank).all()
    
    
    if current_user.is_authenticated:
        return redirect(url_for('main.review'))
    book = Books(rank, title, author, poster, description, publisher)
    return render_template('review.html',rank=rank, title=title, preview=preview, review=review)

@main.route("/account", methods=['GET', 'POST'])
def account():
    form = UpdateAccountForm()
    
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
            
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been activated!', 'success')
        return redirect(url_for('main.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        
    image_file = url_for('static', filename='photos' + current_user.image_file)
    
    return render_template('account.html', title='Account | Welcome to Online Library',form=form)

def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/photos', picture_fn)

    output_size = (125, 125)
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)

    return picture_fn

app/templates/account.html
{% extends "base.html" %} {% block content %}
<div class="container-fluid account">
    <div class="content-section account">
        <div class="media">
            <img class="rounded-circle " src="{{ image_file }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        <div class="row rat">
            <div class="col-md-8 ml-5">
                <form method="POST" action="" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4  acc">Account Info</legend>
                        <div class="form-group">
                            {{ form.username.label(class="form-control-label") }} {% if form.username.errors %} {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                <span>{{ error }}</span> {% endfor %}
                            </div>
                            {% else %} {{ form.username(class="form-control form-control-lg") }} {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.email.label(class="form-control-label") }} {% if form.email.errors %} {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                <span>{{ error }}</span> {% endfor %}
                            </div>
                            {% else %} {{ form.email(class="form-control form-control-lg") }} {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.picture.label() }} {{ form.picture(class="form-control-file") }} {% if form.picture.errors %} {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                            {% endfor %} {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-success") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/base.html
{% extends 'bootstrap/base.html'%} {% block styles %} {{super()}}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
<link rel="stylesheet" href="{{url_for('static', filename = 'css/styles.css') }}">
<link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed |Barlow+Condensed:300&display=swap" rel="stylesheet">

<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{{url_for('static', filename = 'css/styles.css') }}"> {% endblock %}
<!-- Navbar block  -->
{% block navbar %} {% include 'navbar.html' %} {% endblock %}

app/templates/comments.html
{% extends "base.html"%}

{% block content%}

<!-- <div class="container">

  <div class="row">

    <div class="col-sm-6">

      <img src="{{review.image_path}}" class="img-responsive">

    </div> -->

    <div class="col-sm-6">

        <h4>{{format_comment_title | safe}}</h4>

        <p>{{format_comment| safe }}</p>

    </div>

  </div>

</div>

{%endblock%}










<!-- {% extends 'base.html'%}

{% import 'macros.html' as macro%}

{% block content %}

    <div class="container" id="shown_comments">

      <div class="col-md-5">

          <div class="content-section">

              <div class="card">

                <div class="card-header">

                  <span>{{book.title}}</span>

                </div>

                <div class="card-body">

                  <p class="card-text">Thoughts on "{{book.title}}" by {{book.user.username}}</p>

                  <p>{{book.author}}</p>

                </div>

          </div>

          </div>

      </div>

    <div class="col-md-7" id="reviews">

      <div class="class=">

        <h1>Reviews</h1>

          <hr>

          {% if comments %}

              {{macro.displayComments(comments)}}

              <a class="btn btn-warning btn-lg text-center" href="/book/comment/new/{{book.rank}}"> Write a comment</a>

          {% else%}

              <h3 class="text-center">This book has no comments </h3>

              <a class="btn btn-warning btn-lg text-center" href="/book/comment/new/{{book.rank}}"> Write a comment</a>

          {% endif %}

      </div>

    </div>

    </div>

    </div>

{% endblock %}
 -->

app/templates/index.html
{% extends 'base.html' %} {% import 'macros.html' as macro %} {% block content %}
<div class="container">
    <h2 class="text-center head animated fadeInLeft">~ Novel App ~</h2>
    <div class="animated slideInRight">
        {{ macro.displayBookList(book) }}
    </div>
</div>
{% endblock %}

app/templates/macros.html
<div class="container">

    <div class="row">
        {% macro displayBookList(book_list) %} {% for book in book_list %}
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-2 mr-5 ">
            <a href="{{url_for('main.review')}}"> <img src="{{book.poster}}" alt="" class="img-thumbnail view-overlay zoom" style="width: 200px; height: 200px;">
                <h3>
            </a>
            <!-- <a href="{{url_for('main.review')}}">{{book.title}}</a></h3> -->
        </div>
        {% endfor %} {% endmacro %} {% macro displaycomment(comment_list) %} {% for review in comment_list %}
    </div>
</div>


<div class="row">

    <div class="col-xs-2 col-sm-2 col-md-4 col-lg-4">

        <h4>Author</h4>

        <p>{{comment.user.username}}</p>

    </div>

    <div class="col-xs-10 col-sm-10 col-md-4 col-lg-8">

        <h2><a href="{{url_for('main.new_comment', id = comment.id)}}">

                {{comment.comment_title}}

            </a></h2>

    </div>

</div>

{% endfor %} {% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse fixed-top" role="navigation" style="border-radius: 0;">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" style="font-size: 20px;">Novel App</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}"><i class="fa fa-fw fa-home"></i>Home</a></li>
                <li style="text-align: center;">
                    <!-- <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit"><i
                                class="fa fa-search"></i></button>
                    </form> -->
                </li>
            </ul>

            <div class="navbar-collapse collapse navbar-right">
                <ul class="nav navbar-nav navbar-right">
                    {%if current_user.is_authenticated%}
                    <li style="color:white">
                        {%if current_user.profile_pic_path%}
                        <img src="{{url_for('static', filename = current_user.profile_pic_path)}}" alt="dp" style="border-radius:50%" width="40" height="40" style="margin-top: 10px;">
                    </li>

                    <li>
                        {%endif%}
                        <li>

                            <a href="{{url_for('main.account', uname = current_user.username)}}"><i
                                class="fa fa-fw fa-user"></i>{{current_user.username}}</a>
                        </li>
                        <li><a href="{{url_for('auth.logout')}}"><i class="fa fa-sign-out"></i>Logout</a></li>

                        {%else%}
                        <li><a href="{{url_for('auth.login')}}" style="color: #fff;"><i
                                class="fa fa-fw fa-user"></i>Login</a></li>
                        <li>
                            <a href="{{url_for('auth.register')}}"> <i class="fa fa-dot-circle-o"></i> Register</a>
                        </li>
                        {%endif%}

            </div>
        </div>
    </div>
</div>

app/templates/new_comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html'as wtf%}

{% block content %}
<div  class="container">
     
    <div class="col-md-8- big">
    {{ wtf.quick_form(comment_form) }}
    
    </div>

</div>
{% enblock %}

app/templates/review.html
{%extends "base.html"%}
{% import 'macros.html' as macro%}
{% block content %}
    <div class="container">
        <!-- Poster background -->
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 posterPath">
                <img src="{{book.poster}}" alt="{{book.title}}" class="img-responsive">
            </div>   
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 book-details">
                <div class="thumbnail" style="border: none">
                    <h1>{{ book.title }}</h1>   
                    <p class="description"> {{ book.description }}</p>
                    <p class="author"> <b> {{ book.author }}</b></p>
                    <p class="publisher"> <b> {{ book.publisher }}</b></p>   
                </div>
                <h3>Reviews</h3>
                <hr>
                {% if reviews %}
                    {{macro.displayReview(review)}}
                    <a class="btn btn-success text-center" href="/book/review/new/{{book.rank}}"> Write a new reviews</a>      
                {% else%}
                    <h3 class="text-center">This book has no reviews </h3>
                    <a class="btn btn-success text-center" href="/book/review/new/{{book.rank}}"> Write a new review</a>
                {% endif %}
            </div>
        </div> 
    </div>
{%endblock%}